import { BusinessExpense, Invoice, Product, UserAccount, Branch } from "../types";

export const generateDailyReportText = (
  date: string,
  invoices: Invoice[],
  expenses: BusinessExpense[],
  products: Product[],
  branchId?: string
) => {
  const dayInvoices = invoices.filter(inv => inv.date.startsWith(date) && (!branchId || inv.branchId === branchId));
  const dayExpenses = expenses.filter(exp => exp.date.startsWith(date) && (!branchId || exp.branchId === branchId));
  
  const totalSales = dayInvoices.reduce((sum, inv) => sum + inv.grandTotal, 0);
  const cashCollected = dayInvoices.reduce((sum, inv) => sum + inv.amountPaid, 0);
  const totalExpenses = dayExpenses.reduce((sum, exp) => sum + exp.amount, 0);
  const netBalance = cashCollected - totalExpenses;

  const expenseBreakdown = dayExpenses.map(exp => `• ${exp.description}: Rs. ${exp.amount.toLocaleString()}`).join("\n");

  let text = `📊 *DAILY BUSINESS REPORT - ${new Date(date).toLocaleDateString()}*\n`;
  text += `-------------------------------------------\n`;
  text += `💰 Total Sales: Rs. ${totalSales.toLocaleString()}\n`;
  text += `💵 Cash Collected: Rs. ${cashCollected.toLocaleString()}\n`;
  text += `📉 Total Expenses: Rs. ${totalExpenses.toLocaleString()}\n`;
  text += `-------------------------------------------\n`;
  text += `✅ *Net Cash Balance: Rs. ${netBalance.toLocaleString()}*\n\n`;
  
  if (dayExpenses.length > 0) {
    text += `📍 *EXPENSE BREAKDOWN:*\n${expenseBreakdown}\n\n`;
  }

  const lowStock = products.filter(p => p.stockQuantity <= p.minStockAlert);
  if (lowStock.length > 0) {
    text += `⚠️ *LOW STOCK ALERTS:*\n`;
    lowStock.slice(0, 5).forEach(p => {
      text += `• ${p.name}: ${p.stockQuantity} remaining\n`;
    });
    if (lowStock.length > 5) text += `• ...and ${lowStock.length - 5} more items\n`;
  }

  text += `\n📱 Generated by QumberSanitary POS`;
  return text;
};

export const sendToWhatsApp = (phone: string, text: string) => {
  const encodedText = encodeURIComponent(text);
  const url = `https://wa.me/${phone.replace(/[^0-9]/g, "")}?text=${encodedText}`;
  window.open(url, "_blank");
};
